### ISSUE TITLE
[bug] NameError: name 'Literal' is not defined

### ISSUE THREAD

**Issue by mazhewei** [arcstep/langchain_dashscope#1]
file:
venv\lib\site-packages\langchain_dashscope\aigc_generation.py

line 244
in ChatDashScope
    allowed_special: Union[Literal["all"], AbstractSet[str]] = set()

Literal not import, so NameError occur。

to resolve it, add import:
`from typing import Literal`

`Collection` `AbstractSet` same problem

also, import `tiktoken` btw.

**Comment by arcstep** [comment]
Thanks for your advic and you can upgrade now :
```
pip install -U langchain_dashscope==0.1.8
```
